version: '3'

services:
  rabbitmq-service:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test_user
      - RABBITMQ_DEFAULT_PASS=test_pass

    container_name: rabbitmq-service

  payment-service:
    build: ./payment-service
    volumes:
      - .:/code
    ports:
      - 8001:8001
    restart: always
    container_name: payment-service


  order-service:
    build: ./order-service
    volumes:
      - .:/code
    ports:
      - 8002:8002
    restart: always
    container_name: order-service

  catalog-service:
    build: ./catalog-service
    volumes:
      - .:/code
    ports:
      - 8003:8003
    restart: always
    container_name: catalog-service

