version: '3'

volumes:
  pgdata:


services:

  # api-gateway:
  #   # image: annaksatn/api
  #   container_name: api-gateway
  #   build: ./api-gateway
  #   ports:
  #     - 9000:80
  #   restart: always
  #   links:
  #     - payment-service
  #     - order-service
  #     - catalog-service
  #   depends_on:
  #     - payment-service
  #     - order-service
  #     - catalog-service
  #     - db

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "pass"
    ports:
      - "15672:15672"
      - "5672:5672"


#######################
#### ORDER SERVICE ####
#######################

  order-database:
    image: postgres:9.6
    container_name: order-database
    environment:
      POSTGRES_USER: 'order'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'orders'
    # volumes: 
    #   - ./pgdata:/var/lib/pgsql/data
      # - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  order-service: &order-service
    # image: annaksatn/order
    container_name: order-service
    build: ./order-service
    command: bash -c "python3 ./manage.py makemigrations  && python3 ./manage.py migrate && python3 ./manage.py runserver 0.0.0.0:80"
    ports:
      - 9002:80
    depends_on:
      - rabbitmq
      - order-celery
      - order-database

  order-celery:
    <<: *order-service
    restart: always
    command:  bash -c "celery -A order_service worker"
    container_name: order-celery
    ports: []
    depends_on:
      - rabbitmq
      - order-database


#########################
#### PAYMENT SERVICE ####
#########################

  payment-service: &payment-service
    # image: annaksatn/payment
    container_name: payment-service
    build: ./payment-service
    ports:
      - 9001:80
    restart: always
    depends_on:
      - rabbitmq
      - payment-celery


  payment-celery:
    <<: *payment-service
    command: celery -A payment_service worker -B
    container_name: payment-celery
    ports: []
    depends_on:
      - rabbitmq

#########################
#### CATALOG SERVICE ####
#########################

  # catalog-service:
  #   # image: annaksatn/catalog
  #   container_name: catalog-service
  #   build: ./catalog-service
  #   ports:
  #     - 9003:80
  #   restart: always



