version: '3'

services:
  api-gateway:
    # image: annaksatn/api
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - 9000:80
    restart: always
    links:
      - payment-service
      - order-service
      - catalog-service
    depends_on:
      - payment-service
      - order-service
      - catalog-service

  payment-service:
    # image: annaksatn/payment
    container_name: payment-service
    build: ./payment-service
    ports:
      - 9001:80
    restart: always

  order-service:
    # image: annaksatn/order
    container_name: order-service
    build: ./order-service
    ports:
      - 9002:80
    restart: always

  catalog-service:
    # image: annaksatn/catalog
    container_name: catalog-service
    build: ./catalog-service
    ports:
      - 9003:80
    restart: always
