# Generated by Django 2.2.6 on 2019-10-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120, verbose_name='Имя')),
                ('status', models.CharField(choices=[('COLLECTING', 'COLLECTING'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('SHIPPING', 'SHIPPING'), ('CANCELLED', 'CANCELLED'), ('COMPLETE', 'COMPLETE')], max_length=10, verbose_name='Статус заказа')),
                ('totalCost', models.FloatField(default=0.0)),
                ('totalAmount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ReservedItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_service.Order')),
            ],
            options={
                'verbose_name': 'Зарезервированный товар',
                'verbose_name_plural': 'Зарезервированные товары',
                'db_table': 'reserved_items',
            },
        ),
    ]
