# Generated by Django 2.2.6 on 2019-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveditem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
