FROM python:3.7.4-alpine

ENV PYTHONUNBUFFERED 1

RUN mkdir /code

WORKDIR /code
COPY . .

RUN pip install -r requirements.txt
CMD python ./catalog-service/manage.py makemigrations && python ./catalog-service/manage.py migrate && python ./catalog-service/manage.py runserver 0.0.0.0:8003