# Generated by Django 2.2.6 on 2019-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('paymentStatus', models.CharField(choices=[('PAYING', 'PAYING'), ('COMPLETED', 'COMPLETED'), ('RETURNED', 'RETURNED')], max_length=10, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Информация о платеже',
                'verbose_name_plural': 'Информации о платежах',
                'db_table': 'payment_info',
            },
        ),
    ]
