FROM python:3.7.4-alpine

ENV PYTHONUNBUFFERED 1

RUN mkdir /code

WORKDIR /code
COPY . .

RUN pip install -r requirements.txt

CMD python ./payment-service/manage.py makemigrations && python ./payment-service/manage.py migrate && python ./payment-service/manage.py runserver 0.0.0.0:8001